- name: Configure stage instance(s)
  hosts: notifier_stage
  become: True
  vars_files:
    - "{{ secure_dir }}/vars/stage/notifier.yml"
    - "{{ secure_dir }}/vars/users.yml"
  gather_facts: True
  roles:
    - aws
    - role: virtualenv
      virtualenv_user: "notifier"
      virtualenv_user_home: "/opt/wwc/notifier"
      virtualenv_name: "notifier"
    - notifier

- name: Configure loadtest instance(s)
  hosts: notifier_loadtest
  become: True
  vars_files:
    - "{{ secure_dir }}/vars/loadtest/notifier.yml"
    - "{{ secure_dir }}/vars/users.yml"
  gather_facts: True
  roles:
    - aws
    - role: virtualenv
      virtualenv_user: "notifier"
      virtualenv_user_home: "/opt/wwc/notifier"
      virtualenv_name: "notifier"
    - notifier

- name: Configure stage edge instance(s)
  hosts: notifier_edge_stage
  become: True
  vars_files:
    - "{{ secure_dir }}/vars/edge_stage/notifier.yml"
    - "{{ secure_dir }}/vars/users.yml"
  gather_facts: True
  roles:
    - aws
    - role: virtualenv
      virtualenv_user: "notifier"
      virtualenv_user_home: "/opt/wwc/notifier"
      virtualenv_name: "notifier"
    - notifier

- name: Configure prod instance(s)
  hosts: notifier_prod
  become: True
  vars_files:
    - "{{ secure_dir }}/vars/prod/notifier.yml"
    - "{{ secure_dir }}/vars/users.yml"
  gather_facts: True
  roles:
    - aws
    - role: virtualenv
      virtualenv_user: "notifier"
      virtualenv_user_home: "/opt/wwc/notifier"
      virtualenv_name: "notifier"
    - notifier

- name: Configure edge prod instance(s)
  hosts: notifier_edge_prod
  become: True
  vars_files:
    - "{{ secure_dir }}/vars/edge_prod/notifier.yml"
    - "{{ secure_dir }}/vars/users.yml"
  gather_facts: True
  vars:
  roles:
    - aws
    - role: virtualenv
      virtualenv_user: "notifier"
      virtualenv_user_home: "/opt/wwc/notifier"
      virtualenv_name: "notifier"
    - notifier
