# Configure a Jenkins worker instance
# This has all the requirements to run sitespeedio,
# but not the Jenkins Java app, or edx-platform.

- name: Configure instance(s)
  hosts: jenkins_worker
  become: True
  gather_facts: True
  vars:
    mongo_enable_journal: False
    serial_count: 1
    sitespeed_worker: True
    COMMON_SECURITY_UPDATES: yes
    SECURITY_UPGRADE_ON_ANSIBLE: true
  serial: "{{ serial_count }}"
  vars_files:
    - roles/edxapp/defaults/main.yml
    - roles/xqueue/defaults/main.yml
    - roles/xserver/defaults/main.yml
    - roles/forum/defaults/main.yml
  roles:
    - aws
    - jenkins_worker
