- name: Deploy edX Programs Service
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_DATADOG: False
    ENABLE_SPLUNKFORWARDER: False
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'programs'
  roles:
    - aws
    - role: nginx
      nginx_sites:
        - programs
      nginx_default_sites:
        - programs
    - programs
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
