---
# Currently the only difference between these requierements and the role
# defaults is the presence of the "testing.txt" file, which is used to install
# packages not used in production
pre_requirements_file:    "{{ edxapp_code_dir }}/requirements/edx/pre.txt"
github_requirements_file: "{{ edxapp_code_dir }}/requirements/edx/github.txt"
custom_requirements_file:   "{{ edxapp_code_dir }}/requirements/edx/custom.txt"
local_requirements_file:  "{{ edxapp_code_dir }}/requirements/edx/local.txt"
base_requirements_file:   "{{ edxapp_code_dir }}/requirements/edx/base.txt"
post_requirements_file:   "{{ edxapp_code_dir }}/requirements/edx/post.txt"
paver_requirements_file:   "{{ edxapp_code_dir }}/requirements/edx/paver.txt"
testing_requirements_file:   "{{ edxapp_code_dir }}/requirements/edx/testing.txt"

edxapp_requirements_files:
  - "{{ pre_requirements_file }}"
  - "{{ github_requirements_file }}"
  - "{{ custom_requirements_file }}"
  - "{{ local_requirements_file }}"
  - "{{ base_requirements_file }}"
  - "{{ post_requirements_file }}"
  - "{{ paver_requirements_file }}"
  - "{{ testing_requirements_file }}"
