# Usage: ansible-playbook -i jenkins-host, -e@path/to/jenkins-extra-vars.yml -e@path/to/secure.yml -e 'COMMON_ENABLE_NEWRELIC=false' -e 'COMMON_ENABLE_DATADOG=false'

- name: Configure instance(s)
  hosts: all
  become: True
  roles:
  - jenkins_analytics
