# ansible-playbook -i 'admin.edx.org,' ./hotg.yml -e@/path/to/ansible/vars/edx.yml -e@/path/to/secure/ansible/vars/edx_admin.yml

- name: Install go-agent-docker-server
  hosts: all
  become: True
  gather_facts: True
  roles:
  - aws
  - go-agent-docker-server
